/* Builds assets/land.js from assets/world.js.
 *
 *   node tools/make-land.mjs
 *
 * The front page draws the Earth about seventy pixels across. At that size the
 * borders dataset is eighty kilobytes of detail nobody can see, and it is the
 * wrong shape anyway: what the disc needs is coastline, not countries. So the
 * country polygons are merged into one list of rings, the small islands are
 * dropped, and what is left is simplified until a point is worth roughly half
 * a pixel on the disc.
 *
 * Run it again whenever world.js changes. The output says what made it and
 * from what, so a stale land.js can be spotted without diffing it.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';

const SRC = 'assets/world.js';
const OUT = 'assets/land.js';

/* A ring has to cover about this much of the sphere to be drawn at all. The
 * disc is ~70px across, so anything smaller than a couple of square degrees is
 * a pixel at best. Iceland (~0.5°²... ) — see the check below: the threshold is
 * tuned so that Iceland, Ireland, Sicily and Hokkaido survive and the Azores
 * do not. */
const MIN_AREA_DEG2 = 2.5;

/* Douglas-Peucker tolerance in degrees. At 70px across, one degree of latitude
 * is about a fifth of a pixel, so 1.1° keeps every coastline feature a reader
 * could possibly resolve and throws away the rest. */
const TOLERANCE_DEG = 1.1;

const raw = readFileSync(SRC, 'utf8');
const window = {};
new Function('window', raw)(window);
const world = window.WORLD;
if (!world || !Array.isArray(world.c)) throw new Error('world.js did not define WORLD.c');

/* ---- geometry ---- */

function area(ring) {                       // shoelace, in square degrees
  let a = 0;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    a += ring[j][0] * ring[i][1] - ring[i][0] * ring[j][1];
  }
  return Math.abs(a) / 2;
}

function perpDistance(p, a, b) {
  const dx = b[0] - a[0], dy = b[1] - a[1];
  const len2 = dx * dx + dy * dy;
  if (!len2) return Math.hypot(p[0] - a[0], p[1] - a[1]);
  let t = ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / len2;
  t = Math.max(0, Math.min(1, t));
  return Math.hypot(p[0] - (a[0] + t * dx), p[1] - (a[1] + t * dy));
}

function simplify(ring, tol) {
  if (ring.length < 4) return ring;
  const keep = new Array(ring.length).fill(false);
  keep[0] = keep[ring.length - 1] = true;
  const stack = [[0, ring.length - 1]];
  while (stack.length) {
    const [lo, hi] = stack.pop();
    let worst = -1, at = -1;
    for (let i = lo + 1; i < hi; i++) {
      const d = perpDistance(ring[i], ring[lo], ring[hi]);
      if (d > worst) { worst = d; at = i; }
    }
    if (worst > tol) {
      keep[at] = true;
      stack.push([lo, at], [at, hi]);
    }
  }
  return ring.filter((_, i) => keep[i]);
}

/* A ring that crosses the antimeridian arrives split across ±180 in the source
 * data; drawn on a sphere that is harmless, because every point is projected
 * on its own. Nothing to do here but carry the coordinates through. */

const rings = [];
let dropped = 0;
for (const country of world.c) {
  for (const poly of country.p || []) {
    for (const ring of poly) {
      if (!Array.isArray(ring) || ring.length < 4) { dropped++; continue; }
      if (area(ring) < MIN_AREA_DEG2) { dropped++; continue; }
      const thin = simplify(ring, TOLERANCE_DEG);
      if (thin.length < 4) { dropped++; continue; }
      rings.push(thin.map(([lon, lat]) => [Math.round(lon * 10) / 10,
                                           Math.round(lat * 10) / 10]));
    }
  }
}

rings.sort((a, b) => area(b) - area(a));

const points = rings.reduce((n, r) => n + r.length, 0);
const digest = createHash('sha256').update(raw).digest('hex').slice(0, 12);

const body = '[' + rings.map(r => '[' + r.map(p => '[' + p[0] + ',' + p[1] + ']').join(',') + ']')
                        .join(',\n') + ']';

writeFileSync(OUT,
`/* GENERATED by tools/make-land.mjs from ${SRC} (sha256 ${digest}).
   Do not edit by hand: run \`node tools/make-land.mjs\` instead.

   Coastlines only, merged across countries and simplified to ${TOLERANCE_DEG}°,
   which is about half a pixel on the seventy-pixel Earth the front page draws.
   Rings smaller than ${MIN_AREA_DEG2} square degrees are left out. Largest first,
   so the big landmasses are painted before the islands.

   ${rings.length} rings, ${points} points. */
window.LAND=${body};
`);

console.log(`${rings.length} rings, ${points} points, ${dropped} rings dropped`);
console.log(`${OUT}: ${(readFileSync(OUT).length / 1024).toFixed(1)} KB`);
